/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulationproject;

import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Peter
 */
public class Simulated_Data extends javax.swing.JFrame {

    /**
     * Creates new form Simulated_Data
     */
    public Simulated_Data() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Monto Carlo modeling");
//         data dat=new data();
//           dat.deleteData();

        loadData();

    }

    public void loadData() {
//        data2 dat=new data2();
//        dat.loadFromFile();
        File f = new File("dataa.txt");
        if (f.exists() && !f.isDirectory()) {

            fileManger fa = new fileManger();
            ArrayList<Object> dati = fa.read("dataa.txt");
            DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
            String[][] data = new String[dati.size()][3];

            for (int i = 0; i < dati.size(); i++) {
                ArrayList<data2> a = (ArrayList<data2>) (Object) dati;
                data[i][0] = Integer.toString(a.get(i).getDay());
                data[i][1] = Integer.toString(a.get(i).getRandom());

//           tbModel.addRow(new Object[]{data});
                tbModel.addRow(data[i]);

            }
        }

    }

//    public void saveData() {
//        for (int i = 0; i < jTable1.getRowCount(); i++) {
//            data2 dat = new data2();
//            for (int j = 0; j < jTable1.getColumnCount(); j++) {
//
//                if (j == 0) {
//                    dat.setDay(Integer.parseInt(jTable1.getValueAt(i, j).toString()));
//                } else if (j == 1) {
//                    dat.setRandom(Integer.parseInt(jTable1.getValueAt(i, j).toString()));
//                }
//
////            
//            }
//            dat.addTo_file();
//        }
//
//    }
    public void Sim() {
        int sum = 0;
        int num;
        int sim = 0;
        float first;
        float last;
        String gomla;
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        data dat = new data();

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            num = Integer.parseInt(jTable1.getValueAt(i, 1).toString());
            dat.loadFromFile();
            for (int j = 0; j < dat.dati.size(); j++) {
                first = dat.dati.get(j).getFirst();
                last = dat.dati.get(j).getLast();
                if (num >= first && num <= last) {
                    sim = dat.dati.get(j).getDemand();
                    tbModel.setValueAt(sim, i, 2);
                }
            }
        }
    }

    public void getAve() {
        float sum = 0;
        int ave;
        int val;
        String result;
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Float.parseFloat(jTable1.getValueAt(i, 2).toString());

        }
        TXResult.setText(Float.toString(sum / tbModel.getRowCount()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXDays = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Ubdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXResult = new javax.swing.JTextField();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Days");

        TXDays.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TXDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXDaysActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Ubdate.setText("Update");
        Ubdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(TXDays, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Add)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete)
                    .addGap(422, 422, 422)
                    .addComponent(Ubdate)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Add)
                        .addComponent(Delete)
                        .addComponent(Ubdate))
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "Random num", "Simulated daily demand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("AVERAGE DAILY DEMAND ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("FOR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("YOUR PRODUCT");

        TXResult.setEditable(false);
        TXResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXResult.setForeground(new java.awt.Color(0, 255, 0));
        TXResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXResultActionPerformed(evt);
            }
        });

        OK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addComponent(TXResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(OK)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))))
                    .addComponent(TXResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainFrame x = new mainFrame();
        x.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXDaysActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        String txDays = TXDays.getText();

        if (TXDays.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No data entered");

        } else if (!txDays.matches("[0-9]*$")) {
            JOptionPane.showMessageDialog(this, "all data must be integer");
        } else {

            //            listOf_Data x = new listOf_Data(Data_ID, txDemand, txFrequancy);
            //            x.addTo_List();
            tbModel.addRow(new Object[]{txDays});

            TXDays.selectAll();

        }
    }//GEN-LAST:event_TXDaysActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        String txDays = TXDays.getText();

        if (TXDays.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No data entered");

        } else if (!txDays.matches("[0-9]*$")) {
            JOptionPane.showMessageDialog(this, "all data must be integer");
        } else {

            //            listOf_Data x = new listOf_Data(Data_ID, txDemand, txFrequancy);
            //            x.addTo_List();
            tbModel.addRow(new Object[]{txDays});

            TXDays.setText("");

        }

    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();

        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "the table is empty");
        } else if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "no selected row");
        } else {
            tbModel.removeRow(jTable1.getSelectedRow());
            TXDays.setText("");

        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        String txDays = TXDays.getText();

        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "the table is empty");
        } else if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "no selected row");
        }

        tbModel.setValueAt(txDays, jTable1.getSelectedRow(), 0);

        TXDays.setText("");


    }//GEN-LAST:event_UbdateActionPerformed

    private void TXResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXResultActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        
        Random num = new Random();
        int number;
        data2 dat2 = new data2();
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        fileManger fa = new fileManger();
        ArrayList<Object> dati = fa.read("dataa.txt");
        if (dati.isEmpty()) {

            for (int v = 0; v < jTable1.getRowCount(); v++) {
                number = num.nextInt(100) + 1;
                tbModel.setValueAt(number, v, 1);
            }

        } else if (jTable1.getRowCount()> dati.size()) {
            for (int v=dati.size(); v < jTable1.getRowCount(); v++) {
                number = num.nextInt(100) + 1;
                tbModel.setValueAt(number, v, 1);
        }
        }
        Sim();
        getAve();
        dat2.deleteData();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            data2 dat = new data2();
            for (int j = 0; j < jTable1.getColumnCount(); j++) {

                if (j == 0) {
                    dat.setDay(Integer.parseInt(jTable1.getValueAt(i, j).toString()));
                } else if (j == 1) {
                    dat.setRandom(Integer.parseInt(jTable1.getValueAt(i, j).toString()));
                }

            }
            if (i == 0) {
                dat.addTo_fileFalse();
            } else {
                dat.addTo_fileTrue();
            }
        }

    }//GEN-LAST:event_OKActionPerformed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "the table is empty");
            } else if (jTable1.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "no selected row");
            } else {
                tbModel.removeRow(jTable1.getSelectedRow());
                TXDays.setText("");

            }
    }//GEN-LAST:event_jScrollPane1KeyPressed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulated_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulated_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulated_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulated_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulated_Data().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton OK;
    private javax.swing.JTextField TXDays;
    private javax.swing.JTextField TXResult;
    private javax.swing.JButton Ubdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
